/* eslint-disable @typescript-eslint/no-var-requires */
/**
 * Personal-build Chinese localization pass:
 * - Translate plain English command titles in package.json
 * - Polish package.nls.zh-cn.json for personal edition
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

/** Exact title map for contributed commands */
const exact = {
	Refresh: '刷新',
	Copy: '复制',
	'Open Settings': '打开设置',
	'Open View Settings': '打开视图设置',
	'Show Avatars': '显示头像',
	'Hide Avatars': '隐藏头像',
	'Toggle Files View: Tree': '文件列表：树形',
	'Toggle Files View: Auto': '文件列表：自动',
	'Toggle Files View: List': '文件列表：列表',
	'Open File at Revision': '打开修订版本的文件',
	'Show Revision Commit': '显示修订版本的提交',
	'Open File': '打开文件',
	'Toggle View: Tree': '切换为树形视图',
	'Toggle View: List': '切换为列表视图',
	'Show Branch Pull Requests': '显示分支的拉取请求',
	'Hide Branch Pull Requests': '隐藏分支的拉取请求',
	'Show Branch Comparison': '显示分支比较',
	'Hide Branch Comparison': '隐藏分支比较',
	'Add Co-authors': '添加共同作者',
	Fetch: '获取 (Fetch)',
	Pull: '拉取 (Pull)',
	Push: '推送 (Push)',
	'Compare with Selected': '与已选对象比较',
	'Select for Compare': '选中以比较',
	'Show Branch Comparisons': '显示分支比较',
	'Hide Branch Comparisons': '隐藏分支比较',
	'Toggle Filter: Only Current Branch': '筛选：仅当前分支',
	'Toggle Filter: All Branches': '筛选：所有分支',
	'Change Base...': '更改基准...',
	'Unpin the Current History': '取消固定当前历史',
	'Pin the Current History': '固定当前历史',
	'Keep Results': '保留结果',
	'Open in Editor Area': '在编辑器区域打开',
	'Compare References...': '比较引用...',
	'Compare HEAD with...': '比较 HEAD 与...',
	'Compare Working Tree with...': '比较工作区与...',
	'Open Directory Compare (difftool) with...': '用 difftool 比较目录...',
	'Open Directory Compare (difftool)': '用 difftool 比较目录',
	'Disable Interactive Rebase Editor': '禁用交互式变基编辑器',
	'Enable Interactive Rebase Editor': '启用交互式变基编辑器',
	'Computing File Annotations...': '正在计算文件注释...',
	'Toggle Review Mode': '切换审查模式',
	'Toggle Zen Mode': '切换禅模式',
	'Set Views Layout': '设置视图布局',
	'Show Last Opened Quick Pick': '显示上次快捷选择',
	'Reveal Commit in Side Bar': '在侧栏显示提交',
	'Search for Commit in Side Bar': '在侧栏搜索提交',
	'Search for Commits within Selection': '搜索选区内的提交',
	'Show Line Commit': '显示行提交',
	'Quick Open File History': '快速打开文件历史',
	'Connect to Remote': '连接远程',
	'Disconnect from Remote': '断开远程',
	'Close Unchanged Files': '关闭未更改的文件',
	'Open File at Revision from...': '从修订版本打开文件...',
	'Open Issue on Remote': '在远程打开 Issue',
	'Copy Issue Url': '复制 Issue 链接',
	'Open Pull Request on Remote': '在远程打开拉取请求',
	'Copy Pull Request Url': '复制拉取请求链接',
	'Open Associated Pull Request': '打开关联的拉取请求',
	'Open Repository on Remote': '在远程打开仓库',
	'Copy Remote Repository Url': '复制远程仓库链接',
	'Delete Stash...': '删除贮藏...',
	'Stash All Changes': '贮藏全部更改',
	'Stash Changes': '贮藏更改',
	'Open Changes (difftool)': '打开变更 (difftool)',
	'Open All Changes (difftool)': '打开全部变更 (difftool)',
	'Reset Avatar Cache': '重置头像缓存',
	'Reset Suppressed Warnings': '重置已屏蔽的警告',
	'Invite to Live Share': '邀请加入 Live Share',
	'Browse Repository from Revision': '浏览该修订版本的仓库',
	'Browse Repository from Revision in New Window': '在新窗口浏览该修订版本',
	'Browse Repository from Before Revision': '浏览该修订之前的仓库',
	'Browse Repository from Before Revision in New Window': '在新窗口浏览该修订之前的仓库',
	'Repository from Here': '从这里浏览仓库',
	'Repository from Here in New Window': '在新窗口从这里浏览仓库',
	'Repository from Before Here': '从这里之前浏览仓库',
	'Repository from Before Here in New Window': '在新窗口从这里之前浏览仓库',
	'Add Remote': '添加远程',
	'Highlight All Changes Since Before this Commit': '高亮此提交之前以来的所有更改',
	'Highlight Changes from this Commit': '高亮此提交的更改',
	'Show Contributors': '显示贡献者',
	'Hide Contributors': '隐藏贡献者',
	'Show Merge Commits': '显示合并提交',
	'Hide Merge Commits': '隐藏合并提交',
	'Show All Branches': '显示所有分支',
	'Hide All Branches': '隐藏所有分支',
	'Show Worktrees': '显示工作树',
	'Hide Worktrees': '隐藏工作树',
	'Show Stashes': '显示贮藏',
	'Hide Stashes': '隐藏贮藏',
	'Show Tags': '显示标签',
	'Hide Tags': '隐藏标签',
	'Show Remotes': '显示远程',
	'Hide Remotes': '隐藏远程',
	'Show Upstream Status': '显示上游状态',
	'Hide Upstream Status': '隐藏上游状态',
	'Show Section: Branches': '显示分区：分支',
	'Hide Section: Branches': '隐藏分区：分支',
	'Show Section: Remotes': '显示分区：远程',
	'Hide Section: Remotes': '隐藏分区：远程',
	'Show Section: Stashes': '显示分区：贮藏',
	'Hide Section: Stashes': '隐藏分区：贮藏',
	'Show Section: Tags': '显示分区：标签',
	'Hide Section: Tags': '隐藏分区：标签',
	'Show Section: Worktrees': '显示分区：工作树',
	'Hide Section: Worktrees': '隐藏分区：工作树',
	'Show Section: Contributors': '显示分区：贡献者',
	'Hide Section: Contributors': '隐藏分区：贡献者',
	'Copy as Markdown': '复制为 Markdown',
	'Copy as Patch': '复制为 Patch',
	'Copy Remote File Url from Commit': '复制提交中的远程文件链接',
	'Copy Remote File Url from...': '复制远程文件链接...',
	'Open File on Remote from...': '在远程打开文件...',
	'Open Changes with Working File': '与工作区文件比较',
	'Open Changes with Previous Revision': '与上一修订比较',
	'Open Line Changes with Working File': '与工作区比较行变更',
	'Open Line Changes with Previous Revision': '与上一修订比较行变更',
	'Open Working File': '打开工作区文件',
	'Open Changed Files': '打开已更改文件',
	'Open Directory Compare with Working Tree': '与工作区比较目录',
	'Open Directory Compare with...': '比较目录...',
	'Stage All Changes': '暂存全部更改',
	'Unstage All Changes': '取消暂存全部更改',
	'Stage Changes': '暂存更改',
	'Unstage Changes': '取消暂存更改',
	'Apply Changes': '应用更改',
	'Restore (Checkout)': '还原 (Checkout)',
	'Switch to Branch...': '切换到分支...',
	'Create Branch...': '创建分支...',
	'Delete Branch...': '删除分支...',
	'Rename Branch...': '重命名分支...',
	'Rebase Current Branch onto Branch...': '变基当前分支到...',
	'Merge Branch into Current Branch...': '合并分支到当前...',
	'Push to...': '推送到...',
	'Push with Force to...': '强制推送到...',
	'Set as Upstream': '设为上游',
	'Unset Upstream': '取消上游',
	'Star': '收藏',
	'Unstar': '取消收藏',
	'Copy Branch Name': '复制分支名',
	'Copy Remote Name': '复制远程名',
	'Copy Tag Name': '复制标签名',
	'Copy Path': '复制路径',
	'Copy Relative Path': '复制相对路径',
	'Show Commit Details': '显示提交详情',
	'Show Commit Search': '搜索提交',
	'Show Stash Details': '显示贮藏详情',
	'Pop Stash': '弹出贮藏',
	'Apply Stash': '应用贮藏',
	'Drop Stash': '丢弃贮藏',
	'Create Tag...': '创建标签...',
	'Delete Tag...': '删除标签...',
	'Open Worktree...': '打开工作树...',
	'Open Worktree in New Window...': '在新窗口打开工作树...',
	'Create Worktree...': '创建工作树...',
	'Delete Worktree...': '删除工作树...',
	'Copy Worktree Path': '复制工作树路径',
	'Reveal in File Explorer': '在资源管理器中显示',
	'Reveal in Finder': '在 Finder 中显示',
	'Open in Terminal': '在终端中打开',
	'Close Repository': '关闭仓库',
	'Set as Active Repository': '设为活动仓库',
	'Fetch All': '全部获取',
	'Pull All': '全部拉取',
	'Push All': '全部推送',
	'Load more': '加载更多',
	'Load More': '加载更多',
	'Load all': '加载全部',
	'Load All': '加载全部',
	'Show more': '显示更多',
	'Show More': '显示更多',
	'Collapse All': '全部折叠',
	'Expand All': '全部展开',
	'Clear Results': '清除结果',
	'New Search...': '新建搜索...',
	'New Compare...': '新建比较...',
	'Search & Compare': '搜索与比较',
	'Open Comparison on Remote': '在远程打开比较',
	'Swap Comparison': '交换比较方向',
	'Open Changes': '打开变更',
	'Open All Changes': '打开全部变更',
	'Open Files': '打开文件',
	'Open All Files': '打开全部文件',
	'Copy SHA': '复制 SHA',
	'Copy Message': '复制提交说明',
	'Copy Name': '复制名称',
	'Show in Commit Graph': '在提交图中显示',
	'Refresh Graph': '刷新提交图',
	'Show Graph': '显示提交图',
	'Show Timeline': '显示时间线',
	'Refresh Timeline': '刷新时间线',
	'Open Visual File History': '打开可视化文件历史',
	'Show Home': '显示首页',
	'GitLens Settings': 'GitLens 设置',
	'GitLens: Open Settings': '打开 GitLens 设置',
	'Checkout...': '检出...',
	'Checkout': '检出',
	'Merge...': '合并...',
	'Rebase...': '变基...',
	'Cherry-Pick...': '拣选 (Cherry-pick)...',
	'Revert...': '还原 (Revert)...',
	'Reset...': '重置...',
	'Push...': '推送...',
	'Pull...': '拉取...',
	'Fetch...': '获取...',
	'Publish Branch...': '发布分支...',
	'Publish Repository...': '发布仓库...',
	'Create Pull Request...': '创建拉取请求...',
	'Open Pull Request...': '打开拉取请求...',
	'Terminal: Create Branch': '终端：创建分支',
	'Terminal: Delete Branch': '终端：删除分支',
	'Terminal: Rename Branch': '终端：重命名分支',
	'Terminal: Create Tag': '终端：创建标签',
	'Terminal: Delete Tag': '终端：删除标签',
	'Terminal: Cherry Pick': '终端：拣选',
	'Terminal: Merge': '终端：合并',
	'Terminal: Rebase': '终端：变基',
	'Terminal: Reset': '终端：重置',
	'Terminal: Revert': '终端：还原',
	'Terminal: Switch': '终端：切换',
	'Open File Contents from Revision': '打开修订版本文件内容',
	'Open File Contents from Revision...': '打开修订版本文件内容...',
	'Open Changes with Revision...': '与修订版本比较...',
	'Open Changes with Branch or Tag...': '与分支或标签比较...',
	'Open Changes with Working Tree': '与工作区比较',
	'Stage Directory': '暂存目录',
	'Unstage Directory': '取消暂存目录',
	'Restore': '还原',
	'Undo Commit': '撤销提交',
	'Soft Reset to Commit': '软重置到提交',
	'Hard Reset to Commit': '硬重置到提交',
	'Reset Current Branch to Commit...': '重置当前分支到提交...',
	'Rebase Current Branch onto Commit...': '变基当前分支到提交...',
	'Cherry Pick Commit...': '拣选提交...',
	'Revert Commit...': '还原提交...',
	'Create Branch from Commit...': '从提交创建分支...',
	'Create Tag from Commit...': '从提交创建标签...',
	'Switch to Commit...': '切换到提交...',
	'Compare with Working Tree': '与工作区比较',
	'Compare with HEAD': '与 HEAD 比较',
	'Compare Selected': '比较已选',
	'Select for Comparison': '选中以比较',
	'Show Commit in Views': '在视图中显示提交',
	'Search Commits': '搜索提交',
	'Filter Commits': '筛选提交',
	'Only My Commits': '仅我的提交',
	'All Commits': '全部提交',
	'Enable Debug Logging': '启用调试日志',
	'Disable Debug Logging': '禁用调试日志',
	'Show Output Channel': '显示输出通道',
	'Walkthrough: Welcome': '向导：欢迎',
	'Walkthrough: GitLens+': '向导：增强功能',
	'Open Welcome': '打开欢迎页',
	'Open Welcome (Quick Setup)': '打开欢迎页（快速设置）',
	'Show Commit Details Page': '显示提交详情页',
	'显示提交详情': '显示提交详情',
	Prune: '清理 (Prune)',
	'Unset as Default': '取消默认',
	'Add to Favorites': '添加到收藏',
	'Remove from Favorites': '从收藏移除',
	'Add as Co-author': '添加为共同作者',
	Clear: '清除',
	Dismiss: '关闭',
	'Edit...': '编辑...',
	Expand: '展开',
	Hide: '隐藏',
	Pin: '固定',
	Unpin: '取消固定',
	'Clear Filter': '清除筛选',
};

function phraseTranslate(title) {
	if (exact[title]) return exact[title];

	let t = title;
	const rules = [
		[/^Show /i, '显示'],
		[/^Hide /i, '隐藏'],
		[/^Open /i, '打开'],
		[/^Toggle /i, '切换'],
		[/^Copy /i, '复制'],
		[/^Compare /i, '比较'],
		[/^Create /i, '创建'],
		[/^Delete /i, '删除'],
		[/^Rename /i, '重命名'],
		[/^Refresh /i, '刷新'],
		[/^Reset /i, '重置'],
		[/^Stage /i, '暂存'],
		[/^Unstage /i, '取消暂存'],
		[/^Stash /i, '贮藏'],
		[/^Fetch /i, '获取'],
		[/^Pull /i, '拉取'],
		[/^Push /i, '推送'],
		[/^Browse /i, '浏览'],
		[/^Invite /i, '邀请'],
		[/^Connect /i, '连接'],
		[/^Disconnect /i, '断开'],
		[/^Enable /i, '启用'],
		[/^Disable /i, '禁用'],
		[/^Load /i, '加载'],
		[/^Close /i, '关闭'],
		[/^Apply /i, '应用'],
		[/^Restore /i, '还原'],
		[/^Highlight /i, '高亮'],
		[/^Search /i, '搜索'],
		[/^Reveal /i, '显示'],
		[/^Set /i, '设置'],
		[/^Switch /i, '切换'],
		[/^Merge /i, '合并'],
		[/^Rebase /i, '变基'],
		[/^Publish /i, '发布'],
		[/^Checkout /i, '检出'],
	];

	for (const [re, rep] of rules) {
		if (re.test(t)) {
			t = t.replace(re, rep);
			break;
		}
	}

	// leftover common English tokens
	const tokens = [
		[/Working Tree/gi, '工作区'],
		[/Working File/gi, '工作区文件'],
		[/File History/gi, '文件历史'],
		[/Line History/gi, '行历史'],
		[/Pull Request/gi, '拉取请求'],
		[/Commit Graph/gi, '提交图'],
		[/Side Bar/gi, '侧栏'],
		[/View Settings/gi, '视图设置'],
		[/All Changes/gi, '全部更改'],
		[/Unchanged Files/gi, '未更改的文件'],
		[/Remote/gi, '远程'],
		[/Repository/gi, '仓库'],
		[/Repositories/gi, '仓库'],
		[/Branches?/gi, '分支'],
		[/Commits?/gi, '提交'],
		[/Stashes?/gi, '贮藏'],
		[/Tags?/gi, '标签'],
		[/Worktrees?/gi, '工作树'],
		[/Contributors?/gi, '贡献者'],
		[/Revision/gi, '修订版本'],
		[/Avatars?/gi, '头像'],
		[/Settings?/gi, '设置'],
		[/Comparison/gi, '比较'],
		[/Compare/gi, '比较'],
		[/Changes?/gi, '更改'],
		[/Files?/gi, '文件'],
		[/Folder/gi, '文件夹'],
		[/History/gi, '历史'],
		[/Details/gi, '详情'],
		[/Message/gi, '说明'],
		[/Name/gi, '名称'],
		[/Path/gi, '路径'],
		[/Url/gi, '链接'],
		[/URL/gi, '链接'],
		[/from Before/gi, '从之前'],
		[/from Here/gi, '从这里'],
		[/in New Window/gi, '在新窗口'],
		[/with Working/gi, '与工作区'],
		[/with Previous/gi, '与上一'],
		[/with Selected/gi, '与已选'],
		[/for Compare/gi, '以比较'],
		[/\.\.\.$/g, '...'],
	];

	for (const [re, rep] of tokens) {
		t = t.replace(re, rep);
	}

	// if still mostly English letters, prefix note
	if (/[A-Za-z]{6,}/.test(t) && !/[\u4e00-\u9fff]/.test(t)) {
		return t; // leave rare leftovers
	}
	return t;
}

// --- package.json commands ---
const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
let translated = 0;
let left = 0;
for (const c of pkg.contributes.commands || []) {
	const t = c.title || '';
	if (t.startsWith('%') || /[\u4e00-\u9fff]/.test(t)) continue;
	const zh = phraseTranslate(t);
	if (zh !== t) {
		c.title = zh;
		translated++;
	} else {
		left++;
		if (left <= 30) console.log('untranslated:', t);
	}
}
// menus may have titles too? usually command refs
pkg.version = '12.1.4';
fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, '\t')}\n`);
console.log('commands translated', translated, 'left', left);

// --- package.nls.zh-cn.json polish ---
const zhPath = path.join(root, 'package.nls.zh-cn.json');
const enPath = path.join(root, 'package.nls.json');
const zh = JSON.parse(fs.readFileSync(zhPath, 'utf8'));
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

const overrides = {
	'gitlens.displayName': 'GitLens 个人版',
	'gitlens.description':
		'个人长期自用：行追溯、提交/文件历史、提交详情、CodeLens。无账号、无试用、无营销。大仓库默认延迟加载文件详情。',
	'views.title': 'GitLens',
	'views.inspect.title': '检视',
	'views.repositories.title': '仓库',
	'views.fileHistory.title': '文件历史',
	'views.commits.title': '提交',
	'views.branches.title': '分支',
	'views.remotes.title': '远程',
	'views.stashes.title': '贮藏',
	'views.tags.title': '标签',
	'views.contributors.title': '贡献者',
	'views.searchAndCompare.title': '搜索与比较',
	'views.worktrees.title': '工作树',
	'views.lineHistory.title': '行历史',
	'views.graph.title': '提交图',
	'views.timeline.title': '可视化文件历史',
	'views.home.title': '首页',
	'config.gitlens.currentLine.enabled':
		'是否在当前行末尾显示「谁改的 / 何时改的」追溯信息。可用命令「切换行追溯」临时开关。',
	'config.gitlens.codeLens.enabled':
		'是否在文件顶部显示 Git CodeLens（作者/最近修改）。可用命令「切换 Git 代码透镜」临时开关。',
	'command.toggleFileBlame.title': '切换文件追溯',
	'command.toggleLineBlame.title': '切换行追溯',
	'command.toggleFileHeatmap.title': '切换文件热力图',
	'command.toggleFileChanges.title': '切换文件变更高亮',
	'command.clearFileAnnotations.title': '清除文件注释',
	'command.toggleCodeLens.title': '切换 Git 代码透镜',
	'command.showWelcomePage.title': '欢迎与快速设置',
	'command.getStarted.title': '使用入门',
	'command.openSettings.title': '打开设置',
	'command.gitCommands.title': 'Git 命令面板',
	'command.showTimelinePage.title': '打开当前文件的可视化历史',
	'command.showTimelineView.title': '显示可视化文件历史',
	'home.welcome.title': '欢迎使用 GitLens 个人版',
	'home.welcome.seeWhatsNew': '使用说明',
	'home.welcome.whatsNew': '使用说明',
	'home.welcome.description':
		'本扩展是<strong>个人精简版</strong>：看谁改了代码、浏览提交历史、打开提交详情与文件历史。已去掉账号、试用和营销弹窗。',
	'home.welcome.quickSetup': '打开设置',
	'home.welcome.getStarted': '打开提交历史',
	'home.welcome.setupDescription':
		'建议先从「提交」视图看历史；光标移到代码行可看行尾追溯。需要时再到设置里微调。',
	'home.welcome.dismiss': '不再显示',
	'home.links.getStarted': '快速开始',
	'home.links.common': '常用功能',
	'home.links.walkthrough': '使用说明',
	'home.links.quickSetup': '快速设置',
	'home.links.settingsEditor': '设置',
	'home.links.restoreWelcome': '恢复欢迎提示',
	'home.links.help': '帮助',
	'home.links.documentation': '说明',
	'home.links.plusFeatures': '高级功能（本版已解锁）',
	'home.links.plusWalkthrough': '高级功能说明',
	'welcome.title': '欢迎使用 <span class="highlight">GitLens 个人版</span>',
	'welcome.seeWhatsNew': '使用说明',
	'welcome.whatsNewIn': '本版说明',
	'welcome.releaseNotes': '更新说明',
	'welcome.walkthrough': '使用入门',
	'welcome.plusFeatures': '高级功能（已解锁，无需账号）',
	'welcome.powerfulBlurb':
		'个人版保留最常用能力：行追溯、CodeLens、提交/文件历史、提交详情。觉得碍眼可在下面关闭 CodeLens 或行追溯。',
	'welcome.settingsEditor': '打开完整设置',
	'welcome.currentLineBlame': '当前行追溯',
	'welcome.currentLineBlameHint': '在当前行末尾显示作者与修改时间',
	'welcome.codeLens': 'Git 代码透镜',
	'welcome.codeLensHint': '在文件顶部显示最近修改与作者信息',
	'welcome.statusBarBlame': '状态栏追溯',
	'welcome.statusBarBlameHint': '在状态栏显示当前行的 Git 信息',
	'welcome.views': '侧栏视图',
	'welcome.viewsBlurb': '默认展开「提交」与「文件历史」，其它视图可按需打开。',
	'welcome.viewsSourceControl': '源代码管理布局',
	'welcome.viewsGitLens': 'GitLens 布局',
	// Plus marketing slots — personal edition: no paywall copy
	'home.state.paid.title': '个人版已解锁',
	'home.state.paid.thanks': '高级能力可用，无需登录。',
	'home.state.paid.info': '提交图、可视化历史等工作在本版可直接使用（部分入口已精简）。',
	'home.state.paid.manage': '打开设置',
	'home.plus.trial.title': '个人版',
	'home.plus.trial.description': '无需试用，功能已开放。',
	'home.plus.trial.upgrade': '',
	'home.plus.trial.upgradeButton': '',
	'home.plus.trial.learnMore': '使用说明',
	'home.preview.info': '',
	'home.plus.info': '个人版不要求 GitKraken 账号。',
	'home.preview.title': '个人版提示',
	'home.preview.description': '可直接使用可视化文件历史等功能。',
	'home.preview.signIn': '',
	'home.preview.upgradePrompt': '',
	'home.preview.plusTitle': '已解锁',
	'home.preview.plusDescription': '本构建为个人精简版。',
	'home.preview.firstFeatures': '推荐：提交历史、文件历史、行追溯。',
	'walkthrough.plus.signIn.markdown': '个人版无需登录。',
	plan: 'GitLens 个人版',
};

for (const [k, v] of Object.entries(overrides)) {
	zh[k] = v;
}

// Fill any missing keys from en with a soft Chinese prefix so nothing falls back to empty
for (const k of Object.keys(en)) {
	if (zh[k] == null || zh[k] === '') {
		const e = en[k];
		if (typeof e === 'string' && e.length) {
			// leave brand names
			if (/^(Slack|Twitter|GitHub|GitLens)$/i.test(e.trim())) {
				zh[k] = e;
			} else {
				zh[k] = e; // keep until better translation; empty is worse
			}
		} else {
			zh[k] = e;
		}
	}
}

fs.writeFileSync(zhPath, `${JSON.stringify(zh, null, 4)}\n`);
console.log('nls zh keys', Object.keys(zh).length);
console.log('done');
